---
# Install additional packages for development Java and other apps
#
# requirements: ansible needs to be installed
# run with:
# ansible-playbook -K ansible-development-environment.yml
#
- name: Customize development environment
  hosts: 127.0.0.1
  connection: local
  become: true
  
  vars:
    pkgs:
      - rsync
      - git
      - git-cola
      - subversion
      - curl
      - php8.1
      - php8.1-curl
      - php8.1-gd
      - php8.1-intl
      - php8.1-mbstring
      - php8.1-xml
      - php8.1-redis
      - php8.1-sqlite3
      - php8.1-pdo-sqlite
      - php8.1-zip
      - php8.1-soap
      - composer # for php
      - openjdk-11-jdk
      - openjdk-11-source
      - adoptopenjdk-11-hotspot
      - gradle
      - kcachegrind # for xdebug profiling php applications
      - maven
      - pwgen # for generating random passwords
      - pandoc # for converting documents, for example MD to ODT
      - texlive-latex-recommended # helper packages for pandoc 
      - texlive-latex-extra # helper packages for pandoc 
      - poedit # for editing gettext translations
      - libxml2-utils # xmllint
      - python3-pip # for python modules
      - libcanberra-gtk-module # for Netbeans 12
      - libcanberra-gtk3-module # for Netbeans 12
      - emacs
      - libappindicator1 # dependency for VPN client for Forti
      - forticlient # VPN client for Forti
      - net-tools # for netstat etc
      - rdesktop # for remote access to Windows 
      - ffmpeg # for video processing tools
      - snapd # for futher snaps
      - clamav # antivirus tool
      - default-mysql-client
      - diffuse # visual diff tool
      - whois
      - adoptopenjdk-8-hotspot
      - filezilla
      - qpdf # for checking PDF form fields
      - recode
      - fasttrack-archive-keyring
      - virtualbox
      - tnef # Microsoft Outlook email attachments using a proprietary format.
      - kubernetes-client
      - helm

  tasks:
  
  - name: First instal additional key package
    package: name=fasttrack-archive-keyring state=present  

  - name: Add an apt signing key 
    # for proxy add: --proxy http://proxy_domain:port 
    apt_key:
     url: "{{ item }}"
     state: present
    loop:
     - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public
     - https://packages.sury.org/php/apt.gpg
     - https://repo.fortinet.com/repo/7.0/ubuntu/DEB-GPG-KEY
     - https://repo.fortinet.com/repo/6.4/ubuntu/DEB-GPG-KEY

  - name: Add custom repository
    apt_repository:
      repo: "{{ item }}"
      state: present
    loop:
       - "deb [arch=amd64] https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ bullseye main" # for JDK 8 adoptopenjdk-8-hotspot
       - "deb https://packages.sury.org/php/ bullseye main" # for JDK 8 adoptopenjdk-8-hotspot
       - "deb https://fasttrack.debian.net/debian-fasttrack/ bullseye-fasttrack main contrib"
       - "deb https://fasttrack.debian.net/debian-fasttrack/ bullseye-backports-staging main contrib"
       #- "deb [arch=amd64] https://repo.fortinet.com/repo/6.4/ubuntu/ /bionic multiverse"
       - "deb [arch=amd64] https://repo.fortinet.com/repo/7.0/ubuntu xenial multiverse"
      
  - name: install packages for development
    package: name={{ pkgs }} state=present  

  - name: Install additional python modules
    pip:
       name: "{{ item }}"
    loop:
      - ansible-lint # lint playbooks
    environment:
      # In case of behing proxy environments pip requires proxy settings in 
      # capitalized variables. 
      #HTTP_PROXY: http://proxy.example.domain:8080
      #HTTPS_PROXY: http://proxy.example.domain:8080

  - name: install snaps for development
    community.general.snap: 
       name: "{{ item }}"
    loop:
      - postman # for web api testing
      - slack # team collaboration

...
