---
# Install additional packages for development Java and other apps
#
# requirements: ansible needs to be installed
# run with:
# ansible-playbook -K ansible-development-environment.yml
#
- name: Customize development environment
  hosts: 127.0.0.1
  connection: local
  become: true
  
  vars:
    pkgs:
      - azure-cli
      - ddev # for local PHP development with docker
      - docker-compose
      - rsync
      - git
      - git-cola
      - gtimelog # time tracking
      - imagemagick
      - subversion
      - curl
      - php8.2
      - php8.2-curl
      - php8.2-gd
      - php8.2-intl
      - php8.2-mbstring
      - php8.2-xml
      - php8.2-redis
      - php8.2-sqlite3
      - php8.2-pdo-sqlite
      - php8.2-zip
      - php8.2-soap
      - composer # for php
      - openjdk-11-jdk
      - openjdk-11-source
      - openjdk-17-jdk
      - openjdk-17-source
      - gradle
      - kcachegrind # for xdebug profiling php applications
      - maven
      - pwgen # for generating random passwords
      - pandoc # for converting documents, for example MD to ODT
      - texlive-latex-recommended # helper packages for pandoc 
      - texlive-latex-extra # helper packages for pandoc 
      - poedit # for editing gettext translations
      - libfuse2 # required by Jetbrains Toolbox App 
      - libimage-exiftool-perl # also installs exiftool CLI tool
      - libxml2-utils # xmllint
      - pipenv
      - python-jinja2 # for ansible templating
      - python3-pip # for python modules
      - python3-venv # for using Python Venv
      - libcanberra-gtk-module # for Netbeans 12
      - libcanberra-gtk3-module # for Netbeans 12
      - emacs
      - libappindicator1 # dependency for VPN client for Forti
      - forticlient # VPN client for Forti
      - net-tools # for netstat etc
      - rdesktop # for remote access to Windows 
      - ffmpeg # for video processing tools
      - snapd # for futher snaps
      - clamav # antivirus tool
      - default-mysql-client
      - diffuse # visual diff tool
      - whois
      - filezilla
      - qpdf # for checking PDF form fields
      - recode
      - fasttrack-archive-keyring
      #- virtualbox # dependency issue on bullseye
      - tnef # Microsoft Outlook email attachments using a proprietary format.
      #- helm
      - tofu
      - yarn

  tasks:
  
  - name: First instal additional key package
    package: name=fasttrack-archive-keyring state=present  

  - name: Add an apt signing key 
    # for proxy add: --proxy http://proxy_domain:port 
    apt_key:
     url: "{{ item }}"
     state: present
    loop:
     - https://repo.fortinet.com/repo/7.0/ubuntu/DEB-GPG-KEY
     - https://repo.fortinet.com/repo/6.4/ubuntu/DEB-GPG-KEY
     - https://repo.fortinet.com/repo/forticlient/7.2/ubuntu/DEB-GPG-KEY
     - https://packages.microsoft.com/keys/microsoft.asc
     - https://get.opentofu.org/opentofu.gpg
     - https://packages.opentofu.org/opentofu/tofu/gpgkey
     - https://pkg.ddev.com/apt/gpg.key
     - https://dl.yarnpkg.com/debian/pubkey.gpg

  - name: Add custom repository
    apt_repository:
      repo: "{{ item }}"
      state: present
    loop:
       - "deb https://fasttrack.debian.net/debian-fasttrack/ bookworm-fasttrack main contrib"
       - "deb https://fasttrack.debian.net/debian-fasttrack/ bookworm-backports-staging main contrib"
       - "deb [arch=amd64] https://repo.fortinet.com/repo/forticlient/7.2/ubuntu/ /stable multiverse"
       - "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli bookworm main"
       - "deb https://packages.opentofu.org/opentofu/tofu/any/ any main"
       - "deb-src https://packages.opentofu.org/opentofu/tofu/any/ any main"
       - "deb http://deb.debian.org/debian bullseye main"
       - "deb-src http://deb.debian.org/debian bullseye main"
       - "deb https://pkg.ddev.com/apt/ * *"
       - "deb https://dl.yarnpkg.com/debian/ stable main"

  - name: install packages for development
    package: name={{ pkgs }} state=present  

  # - name: Install additional python modules
  #   pip:
  #      name: "{{ item }}"
  #   loop:
  #     - ansible-lint # lint playbooks
  #   environment:
  #     # In case of behing proxy environments pip requires proxy settings in 
  #     # capitalized variables. 
  #     #HTTP_PROXY: http://proxy.example.domain:8080
  #     #HTTPS_PROXY: http://proxy.example.domain:8080

  - name: install snaps for development
    community.general.snap: 
       name: "{{ item }}"
    loop:
      - postman # for web api testing
      - slack # team collaboration
      # For Azure AKS (Kubernetes) login. 
      # In case of Azure AKS for AAD enabled cluster you better install with
      # sudo az aks install-cli 
      # to not get errors like: 
      - kubelogin 

  - name: Install eclipse IDE
    ansible.builtin.command: snap install eclipse --classic # requires classic confinement

  - name: Install kubelogin with the Azure "az" CLI command
    ansible.builtin.command: az aks install-cli 
    tags:
      - kubelogin

...
