---
# Install additional packages for Scala / sbt development
#
# requirements: ansible needs to be installed
# run with:
# ansible-playbook -K ansible-scala-environment.yml
#
- name: Customize scala environment on Debian
  hosts: 127.0.0.1
  connection: local
  become: true   

  tasks:
    - name: Add an apt signing key 
      apt_key:
        url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823
        state: present

    - name: Add custom repository
      apt_repository:
        repo: "{{ item }}"
        state: present
        filename: sbt
      loop:
        - "deb https://repo.scala-sbt.org/scalasbt/debian all main"

    - name: install
      package:
       name: "{{ item }}"
       state: present
      loop:
       - sbt

...
