---
# Install additional packages for development Java and other apps
#
# requirements: ansible needs to be installed
# run with:
# ansible-playbook -K ansible-development-environment.yml
#
- name: Customize development environment
  hosts: 127.0.0.1
  connection: local
  become: true
  
  vars:
    pkgs:
      - rsync
      - git
      - subversion
      - curl
      - php
      - "php-xml"
      - "php-sqlite3"
      - "php-zip"
      - openjdk-11-jdk
      - gradle
      - maven
      - pwgen # for generating random passwords
      - pandoc # for converting documents, for example MD to ODT


  tasks:
  - name: install pre-selected packages for development
    package: name={{ pkgs }} state=present  

...
