---
# Install additional packages for debian, which cannot be found
# in standard Debian repositories.
#
# requirements: ansible needs to be installed
# run with:
# ansible-playbook -K ansible-debian-extra-packages.yml
#
- name: Custom packages installation
  hosts: 127.0.0.1
  connection: local
  become: true   

  tasks:
  
   - name: Add custom repository
     apt_repository:
       repo: "{{ item }}"
       state: present
     loop:
        - "deb [arch=amd64] https://packages.microsoft.com/repos/ms-teams stable main"

   - name: Add an apt signing key 
     # for proxy add: --proxy http://proxy_domain:port 
     apt_key:
      url: https://packages.microsoft.com/keys/microsoft.asc
      state: present

   - name: install
     package:
       name: "{{ item }}"
       state: present
     loop:
       - teams

...
