---
# Install additional packages for development Java and other apps
#
# requirements: ansible needs to be installed
# run with:
# ansible-playbook -K ansible-scala-environment.yml
#
- name: Customize scala environment on Debian
  hosts: 127.0.0.1
  connection: local
  become: true   

  tasks:
   - name: Add custom sbt repository
     shell: echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
   - name: Add custom key for apt
     shell: curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | apt-key add
   - name: Update repositories cache
     apt:
       update_cache: yes
   - name: install ...
     package:
       name: "{{ item }}"
       state: present
     loop:
       - sbt

...
