---
# Install additional packages for an update to date NodeJS development
# Installs newer version of Nodejs from external repository.
#
# Setup for Debian buster
#
# requirements: ansible needs to be installed
# run with:
# ansible-playbook -K ansible-debian-node-environment.yml
#
- name: Customize Nodejs environment on Debian
  hosts: 127.0.0.1
  connection: local
  become: true
  vars:
    distribution: bookworm

  tasks:
      
    - name: Add an apt signing key nodesource
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present
      environment:
      #  https_proxy: "https://some-proxy-host:proxy-port"
    
    - name: Add custom Nodejs repository
      apt_repository:
        repo: "{{ item }}"
        state: present
        filename: nodejs
      loop:
       - "deb https://deb.nodesource.com/node_14.x {{ distribution }} main"
       - "deb-src https://deb.nodesource.com/node_14.x {{ distribution }} main"
           
    - name: install nodejs packages
      package:
         name: "{{ item }}"
         state: latest
         force: yes
      loop:
       - nodejs
  
    - name: install system dependencies for Cypress
      package:
         name: "{{ item }}"
         state: latest
         force: yes
      loop:
       - nodejs
       - libgtk2.0-0 
       - libgtk-3-0 
       - libgbm-dev 
       - libnotify-dev 
       - libgconf-2-4 
       - libnss3 
       - libxss1 
       - libasound2
       - libxtst6
       - xauth
       - xvfb

    - name: Install node.js packages globally
      npm:
        name: "{{ item }}"
        global: yes
      loop: 
       - gulp-cli
      tags:
       - node-libs

    - name: Download Node Version Manager for handling multiple node versions see https://github.com/nvm-sh/nvm
      get_url: 
        url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh
        dest: /tmp/nvm-install.sh
        mode: 0755
      become: false
      tags:
       - nvm
    - name: Install Node Version Manager for handling multiple node versions for current user
      shell: /tmp/nvm-install.sh
      become: false
      tags:
       - nvm
      