---
# Install additional packages for development Java and other apps
#
# requirements: ansible needs to be installed
# run with:
# ansible-playbook -K ansible-development-environment.yml
#
- name: Customize development environment
  hosts: 127.0.0.1
  connection: local
  become: true
  
  vars:
    pkgs:
      - rsync
      - git
      - subversion
      - curl
      - php
      - php-curl
      - php-gd
      - php-mbstring
      - php-xml
      - php-redis
      - php-sqlite3
      - php-zip
      - php-soap
      - composer # for php
      - openjdk-11-jdk
      - openjdk-11-source
      - adoptopenjdk-11-hotspot
      - gradle
      - maven
      - pwgen # for generating random passwords
      - pandoc # for converting documents, for example MD to ODT
      - poedit # for editing gettext translations
      - libxml2-utils # xmllint
      - python3-pip # for python modules
      - libcanberra-gtk-module # for Netbeans 12
      - libcanberra-gtk3-module # for Netbeans 12
      - emacs
      - openfortivpn # VPN client for Forti
      - net-tools # for netstat etc
      - rdesktop # for remote access to Windows 
      - ffmpeg # for video processing tools
      - snapd # for futher snaps
      - clamav # antivirus tool
      - default-mysql-client
      - diffuse # visual diff tool
      - whois
      - adoptopenjdk-8-hotspot
      - filezilla
      - qpdf # for checking PDF form fields
      
  tasks:
  
  - name: Add an apt signing key 
    # for proxy add: --proxy http://proxy_domain:port 
    apt_key:
     url: "{{ item }}"
     state: present
    loop:
     - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public
      
  - name: Add custom repository
    apt_repository:
      repo: "{{ item }}"
      state: present
    loop:
       - "deb [arch=amd64] https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ buster main" # for JDK 8 adoptopenjdk-8-hotspot
      
  - name: install packages for development
    package: name={{ pkgs }} state=present  

  - name: Install additional python modules
    pip:
       name: "{{ item }}"
    loop:
      - ansible-lint # lint playbooks
    environment:
      # In case of behing proxy environments pip requires proxy settings in 
      # capitalized variables. 
      #HTTP_PROXY: http://proxy.example.domain:8080
      #HTTPS_PROXY: http://proxy.example.domain:8080

#  - name: install snaps for development
#    community.general.snap: 
#       name: "{{ item }}"
#    loop:
#      - postman # for web api testing

...
