---
# Install additional packages for debian, which cannot be found
# in standard Debian repositories.
#
# requirements: ansible needs to be installed
# run with:
# ansible-playbook -K ansible-debian-extra-packages.yml
# only standard package install
# ansible-playbook -K ansible-debian-extra-packages.yml --tags standard-packages
#
- name: Additional packages installation - both custom and from standard repository
  hosts: 127.0.0.1
  connection: local
  become: true   
  vars:
    pkgs:
      - seahorse-nautilus # for encryion within nautilus file manager
 
  tasks:
   - name: Add custom ms-teams repository
     shell: echo 'deb [arch=amd64] https://packages.microsoft.com/repos/ms-teams stable main' | tee /etc/apt/sources.list.d/teams.list
   - name: Add custom key for apt
     # for proxy add: --proxy http://proxy_domain:port 
     shell: curl -sL "https://packages.microsoft.com/keys/microsoft.asc" | apt-key add
   - name: Update repositories cache
     apt:
       update_cache: yes
   - name: install
     package:
       name: "{{ item }}"
       state: present
     loop:
       - teams

   - name: install standard packages
     package: name={{ pkgs }} state=present
     tags: 
      - standard-packages

...
