---
# Install additional packages for debian, which cannot be found
# in standard Debian repositories.
#
# requirements: ansible needs to be installed
# run with:
# ansible-playbook -K ansible-debian-extra-packages.yml
# only standard package install
# ansible-playbook -K ansible-debian-extra-packages.yml --tags standard-packages
#
- name: Additional packages installation - both custom and from standard repository
  hosts: 127.0.0.1
  connection: local
  become: true   
  vars:
    pkgs:
      - seahorse-nautilus # for encryion within nautilus file manager
 
  tasks:
  
   - name: Add custom repository
     apt_repository:
       repo: "{{ item }}"
       state: present
     loop:
        - "deb [arch=amd64] https://packages.microsoft.com/repos/ms-teams stable main"

   - name: Add an apt signing key 
     # for proxy add: --proxy http://proxy_domain:port 
     apt_key:
      url: https://packages.microsoft.com/keys/microsoft.asc
      state: present

   - name: install
     package:
       name: "{{ item }}"
       state: present
     loop:
       - teams

   - name: install standard packages
     package: name={{ pkgs }} state=present
     tags: 
      - standard-packages

...
