---
# Install common extra packages
#
# requirements: ansible needs to be installed
# run with:
# ansible-playbook -K ansible-common-packages.yml
#
- name: Common Debian customization
  hosts: 127.0.0.1
  connection: local
  become: true
  
  vars:
    pkgs:
      - ausweisapp
      - extrepo

  tasks:

  - name: Add custom repository
    apt_repository:
      repo: "{{ item }}"
      state: present
    loop:
       - "deb http://deb.debian.org/debian bookworm-backports main contrib non-free non-free-firmware"

  - name: install common extra packages
    package: name={{ pkgs }} state=present  

  - name: Enable non-free policy in extrepo
    replace:
      path: /etc/extrepo/config.yaml
      regexp: '^# - non-free'
      replace: '- non-free'

  - name: Enable slack repo via extrepo                                                                                                                                  
    command: extrepo enable slack                                                                                                                                        
    args:                                                                                                                                                                
      creates: /etc/apt/sources.list.d/extrepo_slack.sources                                                                                                             
                                                                                                                                                                         
  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Install slack
    apt:
      name: slack-desktop
      state: present      

...
