---
# Install additional packages for debian, which cannot be found
# in standard Debian repositories.
#
# requirements: ansible needs to be installed
# run with:
# ansible-playbook -K ansible-debian-extra-packages.yml
# only standard package install
# ansible-playbook -K ansible-debian-extra-packages.yml --tags standard-packages
#
- name: Additional packages installation - both custom and from standard repository
  hosts: 127.0.0.1
  connection: local
  become: true   
  vars:
    pkgs:
      - seahorse-nautilus # for encryion within nautilus file manager
      - rustc # for example for keyring for pyhton
      - dos2unix # for line ending conversions
          
  tasks:

   - name: Add an apt signing key 
     # for proxy add: --proxy http://proxy_domain:port 
     apt_key:
      url: "{{ item }}"
      state: present
     loop:
      - https://packages.microsoft.com/keys/microsoft.asc  # for MS teams
      - https://apt.releases.hashicorp.com/gpg # terraform

   - name: Add custom repository
     apt_repository:
       repo: "{{ item }}"
       state: present
     loop:
        - "deb [arch=amd64] https://packages.microsoft.com/repos/ms-teams stable main"
        - "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ buster main"  # for powershell
        - "deb [arch=amd64] https://apt.releases.hashicorp.com buster main" # terraform
        - "deb [arch=amd64] https://packages.microsoft.com/repos/code stable main"
        - "deb [arch=amd64] https://packages.microsoft.com/debian/11/prod bookworm main"
        
   - name: install
     package:
       name: "{{ item }}"
       state: present
     loop:
       - teams
       - powershell
       - azure-cli
       - terraform
       - code # Visual Studio Code
       - dotnet-sdk-6.0
       - dotnet-runtime-6.0
       - dotnet-sdk-3.1
       - dotnet-runtime-3.1
       - azure-functions-core-tools-4

   - name: install standard packages
     package: name={{ pkgs }} state=present
     tags: 
      - standard-packages

...
