---
# Install additional packages for an update to date NodeJS development
# Installs newer version of Nodejs from external repository.
#
# Setup for Debian buster
#
# requirements: ansible needs to be installed
# run with:
# ansible-playbook -K ansible-debian-node-environment.yml
#
- name: Customize Nodejs environment on Debian
  hosts: 127.0.0.1
  connection: local
  become: true   

  tasks:
      
    - name: Add an apt signing key nodesource
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present
      environment:
      #  https_proxy: "https://some-proxy-host:proxy-port"
    
    - name: Add custom Nodejs repository
      apt_repository:
        repo: "{{ item }} buster main"
        state: present
        filename: nodejs
      loop:
       - "deb https://deb.nodesource.com/node_14.x"
       - "deb-src https://deb.nodesource.com/node_14.x"
           
    - name: install nodejs packages
      package:
         name: "{{ item }}"
         state: latest
         force: yes
      loop:
       - nodejs
  
    - name: install system dependencies for Cypress
      package:
         name: "{{ item }}"
         state: latest
         force: yes
      loop:
       - nodejs
       - libgtk2.0-0 
       - libgtk-3-0 
       - libgbm-dev 
       - libnotify-dev 
       - libgconf-2-4 
       - libnss3 
       - libxss1 
       - libasound2
       - libxtst6
       - xauth
       - xvfb
       

    - name: Add an apt signing key for yarn
      apt_key:
        url: https://dl.yarnpkg.com/debian/pubkey.gpg
        state: present
      environment:
      #  https_proxy: "https://some-proxy-host:proxy-port"

    - name: Add custom yarn repository
      apt_repository:
        repo: "{{ item }} buster main"
        state: present
        filename: nodejs
      loop:
       - "deb https://dl.yarnpkg.com/debian/ stable main"
         
    - name: install yarn packages
      package:
         name: "{{ item }}"
         state: latest
         force: yes
      loop:
       - yarn
  
       
