---
# Install additional packages for an update to date NodeJS development
# Installs newer version of Nodejs from external repository.
#
# Setup for Debian buster
#
# requirements: ansible needs to be installed
# run with:
# ansible-playbook -K ansible-debian-node-environment.yml
#
- name: Customize Nodejs environment on Debian
  hosts: 127.0.0.1
  connection: local
  become: true
  vars:
    distribution: bullseye

  tasks:
      
    - name: Add an apt signing key nodesource
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present
      environment:
      #  https_proxy: "https://some-proxy-host:proxy-port"
    
    - name: Add custom Nodejs repository
      apt_repository:
        repo: "{{ item }} {{ distribution }} main"
        state: present
        filename: nodejs
      loop:
       - "deb https://deb.nodesource.com/node_14.x"
       - "deb-src https://deb.nodesource.com/node_14.x"
           
    - name: install packages
      package:
         name: "{{ item }}"
         state: latest
         force: yes
      loop:
       - nodejs
     
  