---
# Installs and sets up Apache JMeter for performance testing.
#
# The jmeter install is done on localhost in the users bin directory 
# in {{ ansible_env.HOME }}/bin/jmeter/...
# If the bin directory does not exist the setup will fail.
#
# Usage:
# ansible-playbook playbook-jmeter.yml
#

- name: Run Apache Jmeter test - for now only preparation
  hosts: 127.0.0.1
  connection: local
  become: false
  vars:
    - jmeter_sub_path: /apache-jmeter-5.6.3
    - jmeter_dl_archive: https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
    - jmeter_plugin_manager_dl: https://repo1.maven.org/maven2/kg/apc/jmeter-plugins-manager/1.10/jmeter-plugins-manager-1.10.jar
    - jmeter_base_dir: "{{ ansible_env.HOME }}/bin/jmeter"

  tasks:  

  - name: Create JMeter base directory
    ansible.builtin.file:
      path: '{{ jmeter_base_dir }}'
      state: directory
    tags:
     - setup

  - name: Download jmeter
    ansible.builtin.get_url:
      url: '{{ jmeter_dl_archive }}'
      dest: '{{ jmeter_base_dir }}'
    tags:
     - setup

  - name: Extract jmeter archive
    ansible.builtin.unarchive:
      src: '{{ jmeter_base_dir }}{{ jmeter_sub_path }}.tgz'
      dest: '{{ jmeter_base_dir }}'
      remote_src: yes
    tags:
     - setup

  - name: Update memory usage of Jmeter
    ansible.builtin.lineinfile:
      path: '{{ jmeter_base_dir }}{{ jmeter_sub_path }}/bin/jmeter'
      regexp: ': "\$\{HEAP:="-Xms.g -Xmx.g -XX:MaxMetaspaceSize=256m"\}"'
      line: ': "${HEAP:="-Xms6g -Xmx6g -XX:MaxMetaspaceSize=256m"}"'
      backup: yes
    tags:
     - setup
     
  - name: Download jmeter plugin manager
    ansible.builtin.get_url:
      url: "{{ jmeter_plugin_manager_dl }}"
      dest: '{{ jmeter_base_dir }}{{ jmeter_sub_path }}/lib/ext/'
    tags:
     - setup

  - name: Download jmeter cmdrunner
    ansible.builtin.get_url:
      url: http://search.maven.org/remotecontent?filepath=kg/apc/cmdrunner/2.3/cmdrunner-2.3.jar
      dest: '{{ jmeter_base_dir }}{{ jmeter_sub_path }}/lib/'
    tags:
     - setup

  - name: jmeter install PluginsManagerCMD
    command: "java -cp {{ jmeter_base_dir }}{{ jmeter_sub_path }}/lib/ext/jmeter-plugins-manager-1.10.jar org.jmeterplugins.repository.PluginManagerCMDInstaller"
    tags:
     - setup

  - name: jmeter install plugins
    command: "{{ jmeter_base_dir }}{{ jmeter_sub_path }}/bin/PluginsManagerCMD.sh install {{ item }}"
    loop:
     - bzm-random-csv=0.8
     - bzm-hls=3.1
    tags:
     - setup

        
    